### ISSUE TITLE
What to do when missing group?

### ISSUE THREAD

**Issue by noreklint** [innosat-mats/level1a-platform#20]
# 📋 Background

We currently require every group to be in the platform data to process it, even if we don't (currently) use the data in subsequent steps.

This caused  MATS_Platform_OPS_LEVEL1A_20230106-134907_20230107-104841.h5 to fail due to missing temperature data.

# ❓ Questions
- What to do in this case? Allow to proceed without temperature data?

**Comment by skymandr** [comment]
My suggestion, based on the information that we've gotten from @donal-mur regarding the way OHB want to deliver data, is to process every h5-file that arrives that we can process, regardless of contents, and save being picky to when we create L1A. (but we will likely need to relax a little there as well).
